# On MacOS, `brew install michaeleisel/zld/zld`
[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-fuse-ld=/opt/homebrew/bin/zld"]

[target.arch64-apple-darwin]
rustflags = ["-C", "link-args=-fuse-ld=/opt/homebrew/bin/zld"]
